
#ifndef CALCULATE_POSITION

#define CALCULATE_POSITION

// THIS FUNCTION USES THE ACCELEROMETER AND GYROSCOPE DATA TO FIGURE OUT THE CURRENT ORIENTATION OF THE QUAD

int calculate_position(int gyro_data, int acc_data);

#endif

